# tmux configs

# Mouse mode on
set -g mouse on
# start windows numbering at 1
set -g base-index 1
# make pane numbering consistent with windows
setw -g pane-base-index 1
# rename window to reflect current program
setw -g automatic-rename on
# renumber windows when a window is closed
set -g renumber-windows on

# enable tmux 256 colors
set -g default-terminal "screen-256color" # colors!
set -ag terminal-overrides ",xterm-256color:RGB"

## extended keys enabled
#set -g extended-keys on
#set -g extended-keys-format csi-u

## https://github.com/3rd/image.nvim/?tab=readme-ov-file#tmux
## This is needed by the image.nvim plugin
set -gq allow-passthrough on

# activity
set -g monitor-activity on
set -g visual-activity off

# pane navigation
bind > swap-pane -D # swap current pane with the next one
bind < swap-pane -U # swap current pane with the previous one

# maximize tmux pane
bind -r m resize-pane -Z

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Open new window in current directory
bind 'c' new-window -c "#{pane_current_path}"

# enable vim mode
set-window-option -g mode-keys vi

# copying text using vim mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
# unbind -T copy-mode-vi MouseDragEnd1Pane

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# theme / style
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'alexwforsythe/tmux-which-key'  # prefix + space
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'dreknix/tmux-primary-ip'
#
# tooling
set -g @plugin 'omerxx/tmux-sessionx'          # prefix + o

### configure plugins

### https://github.com/catppuccin/tmux
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_number_position 'right'
#set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_date_time_text '%d.%m. %H:%M'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'

# source the plugin here
run '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/catppuccin.tmux'

# set left and right status bar
set -g allow-rename off
set -g status-position top
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
set -g status-left '#{E:@catppuccin_status_session} '
set -gF status-right ' '
set -ag status-right '#{E:@catppuccin_status_date_time}'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
