# tmux configs

## # Mouse mode on
set -g mouse on
## # start windows numbering at 1
set -g base-index 1
## # make pane numbering consistent with windows
setw -g pane-base-index 1
## # rename window to reflect current program
setw -g automatic-rename on
## # renumber windows when a window is closed
set -g renumber-windows on

# enable tmux 256 colors
set -g default-terminal "tmux-256color"

## extended keys enabled
set -g extended-keys on
set -g extended-keys-format csi-u

## https://github.com/3rd/image.nvim/?tab=readme-ov-file#tmux
## This is needed by the image.nvim plugin
set -gq allow-passthrough on

# activity
set -g monitor-activity on
set -g visual-activity off

# pane navigation
bind > swap-pane -D # swap current pane with the next one
bind < swap-pane -U # swap current pane with the previous one

# maximize tmux pane
bind -r m resize-pane -Z

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Open new window in current directory
bind 'c' new-window -c "#{pane_current_path}"

# enable vim mode
set-window-option -g mode-keys vi

# set left and right status bar
set -g allow-rename off

# copying text using vim mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
# unbind -T copy-mode-vi MouseDragEnd1Pane

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# theme / style
### https://github.com/catppuccin/tmux
set -g @catppuccin_flavor 'mocha'

# source the plugin here
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_window_text " #(~/.config/tmux/scripts/window-name.sh #{pane_tty} #{b:pane_current_path}) [#{pane_current_command}]"
set -g @catppuccin_window_current_text "#[fg=#{@thm_mantle},bold,bg=#{@thm_mauve}] #(~/.config/tmux/scripts/window-name.sh #{pane_tty} #{b:pane_current_path}) [#{pane_current_command}]"

set -g status-position top
set -g status-right-length 100
set -g status-left ""
#set -g status-right '#[fg=#{@thm_crust},bold,bg=#{@thm_teal}] session: #S '
set -g status-right '#[fg=#{@thm_crust},bold,bg=#{@thm_teal}] #S '

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
