theme = "onedark"
# theme = "nord"

[editor]
# rulers = [120]
cursorline = true
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"

[editor.indent-guides]
render = true
