" Vim Configurations
" ------------------

"
" --------------- General configuration ------------------------
"

set nocompatible
filetype off

set encoding=utf-8
set mouse=a

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'preservim/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tpope/vim-sensible'
Plugin 'arcticicestudio/nord-vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'powerline/powerline'
Plugin 'airblade/vim-gitgutter'
Plugin 'kien/ctrlp.vim'
Plugin 'cespare/vim-toml'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax'
Plugin 'Yggdroot/indentLine'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

"
" --------------- Theme customization ---------------------------
"

set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim/

" Colorschemes
colorscheme nord

" dark background
set background=dark

let g:airline_powerline_fonts=1
let g:airline_theme='nord'

set statusline=%=&P\ %f\ %m

" Cursorline customization
set cursorline
hi CursorLineNr term=bold cterm=bold

"
" ----------------- Syntax customization ----------------------
"

" Syntax
syntax on
set autoindent
set number
set showmatch

" Spacing format
set tabstop=4
set shiftwidth=4
set expandtab

" Custom spacing per filetyle
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" Also highlight all tabs and trailing whitespace characters.
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$\|\t/

" highlight matches
set hlsearch
set ignorecase          " Make searching case insensitive
set smartcase           " ... unless the query has capital letters.

" search as characters are entered
set incsearch


"
" ---------------- Keyboard mapping -----------------------
"

" Custom mapping
" Normal mode
nmap j ddp
nmap k dd<up>P
nmap <C-n> :NERDTreeToggle<CR>

" Insert mode
let mapleader = "\<Space>"

" Toggle line number: space + n
nnoremap <leader>n :set nu!<CR>

" hit space + space to remove highlights
nnoremap <leader><Space> :nohlsearch<CR>

" toggle paste mode
" this ignores indentation rules when pasting
nnoremap <leader>p :set paste! paste?<CR>

" Close buffer window
nnoremap <leader><Backspace> :bd<CR>

" cycle between left and right tabs
nnoremap <leader><right> :tabnext<CR>
nnoremap <leader><left> :tabprev<CR>


"
" -------------- Customization of plugins -------------------
"

" --- ctrlp ---
" configure ctrlp to use ag for searching
" this interacts nicely with the gitignore vim package
let g:ctrlp_use_caching = 0
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor

    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
else
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
  let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<space>', '<cr>', '<2-LeftMouse>'],
    \ }
endif

" -- vim-pandoc
let g:pandoc#modules#disabled = ["folding"]

