"General configuration
" ...........................

set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'preservim/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tpope/vim-sensible'
" Plugin 'morhetz/gruvbox'
Plugin 'arcticicestudio/nord-vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'powerline/powerline'
Plugin 'airblade/vim-gitgutter'
Plugin 'kien/ctrlp.vim'
" Plugin 'valloric/youcompleteme'
Plugin 'cespare/vim-toml'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim/

" Colorschemes
" colorscheme gruvbox
colorscheme nord

" dark background
set background=dark

let g:airline_powerline_fonts=1
let g:airline_theme='nord'

"
" ----------------- Standard customization ----------------------
"

syntax on
set autoindent
set number
set encoding=utf-8
set showmatch

" Also highlight all tabs and trailing whitespace characters.
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$\|\t/

"
" highlight matches
set hlsearch
set ignorecase          " Make searching case insensitive
set smartcase           " ... unless the query has capital letters.

set mouse=a

" search as characters are entered
set incsearch

" expand tab to space
" real tab is now Ctrl-V<Tab>
set tabstop=4
set shiftwidth=4
set expandtab

set statusline=%=&P\ %f\ %m

" Cursorline customization
set cursorline
hi CursorLineNr term=bold cterm=bold

"
" ---------------- Keyboard mapping -----------------------
"

" Custom mapping
" Normal mode
nmap j ddp
nmap k dd<up>P
nmap <C-n> :NERDTreeToggle<CR>

" Insert mode
let mapleader = "\<Space>"

" Toggle line number: space + n
nnoremap <leader>n :set nu!<CR>

" hit space + space to remove highlights
nnoremap <leader><Space> :nohlsearch<CR>

" toggle paste mode
" this ignores indentation rules when pasting
nnoremap <leader>p :set paste! paste?<CR>

" Close buffer window
nnoremap <leader><Backspace> :bd<CR>

" cycle between left and right tabs
nnoremap <leader><right> :tabnext<CR>
nnoremap <leader><left> :tabprev<CR>


"
" -------------- Customization of plugins -------------------
"

"
" --- ctrlp ---
"

" configure ctrlp to use ag for searching
" this interacts nicely with the gitignore vim package
let g:ctrlp_use_caching = 0
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor

    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
else
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
  let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<space>', '<cr>', '<2-LeftMouse>'],
    \ }
endif

"
" -- vim-pandoc
"
let g:pandoc#modules#disabled = ["folding"]

" "
" " --- YouCompleteMe ---
" "
"
" " don't seek confirmation every time ycm_conf file is found
" let g:ycm_confirm_extra_conf = 0
" " let g:ycm_auto_trigger = 0
" let g:ycm_key_list_stop_completion=['<CR>']
"
" " go to definition of variable/type/function under cursor
" nnoremap <leader>d  ::YcmCompleter GoTo<CR>
" " print type of symbol under the cursor
" nnoremap <leader>t  ::YcmCompleter GetType<CR>
" " print type of symbol under the cursor
" nnoremap <leader>f  ::YcmCompleter FixIt<CR>
" " refactor the name under the cursor
" nnoremap <leader>r  ::YcmCompleter RefactorRename<space>
"
" " Warning highlights
" let g:syntastic_warning_symbol = '⚠'
" highlight YcmWarningSign    ctermfg=14
" highlight YcmWarningSection ctermfg=14
" highlight YcmWarningSection cterm=bold
"
" " Error highlights
" let g:syntastic_error_symbol = '✗'
" highlight YcmErrorSign      ctermfg=1
" highlight YcmErrorSection   ctermfg=1
" highlight YcmErrorSection   cterm=bold

